"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import {
  ShieldCheck,
  Lock,
  Server,
  RefreshCcw,
  ClipboardCheck,
  MailCheck,
  Users2,
} from "lucide-react";

const highlightCards = [
  {
    icon: ShieldCheck,
    title: "GDPR ready",
    description:
      "Compliant with UK GDPR, EU GDPR, and the UK Data Protection Act 2018.",
  },
  {
    icon: Server,
    title: "EU/UK hosting",
    description:
      "Customer data stays within reputable UK & EU data centres with redundancy.",
  },
  {
    icon: Lock,
    title: "Security first",
    description:
      "Encryption in transit & at rest, principle of least privilege, 24/7 monitoring.",
  },
];

const policySections = [
  {
    title: "Information we collect",
    description:
      "We only collect information that helps us offer fulfilment, logistics, and support services to your business.",
    items: [
      "Account data such as contact names, job titles, phone numbers, and billing information that you share when requesting a quote or signing a service agreement.",
      "Operational data generated by integrations with your e-commerce platforms or WMS (order IDs, SKU references, shipment details, and performance metrics).",
      "Communication data from emails, chats, calls, or forms so we can follow up on support requests and keep an audit trail.",
    ],
  },
  {
    title: "How we use information",
    description:
      "Every data point has a clear business purpose. We do not sell data and we avoid unnecessary processing.",
    items: [
      "To provide and improve warehousing, pick & pack, kitting, and courier management services you subscribe to.",
      "To deliver proactive support, onboarding, and training, including sharing critical service updates.",
      "To meet contractual obligations, invoicing, fraud prevention, and to maintain accurate internal reporting.",
    ],
  },
  {
    title: "Retention & storage",
    description:
      "We document retention periods and continuously review what we store. When a record is no longer required, it is securely deleted or anonymised.",
    items: [
      "Commercial & tax records: kept for up to 7 years to meet HMRC obligations.",
      "Operational system logs: retained between 12 and 24 months depending on the integration.",
      "Marketing preferences: refreshed every 24 months or sooner if you opt out.",
    ],
  },
  {
    title: "Sharing data with partners",
    description:
      "We work with carefully vetted technology and logistics partners. Each partner signs strict data processing agreements.",
    items: [
      "Technology vendors that power our WMS, analytics dashboards, and customer support tools.",
      "Freight, carrier, and customs agents involved in fulfilling your orders or receiving inventory.",
      "Professional advisors (legal, compliance, auditors) when legally required and under confidentiality.",
    ],
  },
];

const rightsList = [
  {
    title: "Access & portability",
    description:
      "Request a copy of the information we hold and receive it in a portable format within 30 days.",
  },
  {
    title: "Rectification",
    description:
      "Update inaccurate records so our systems reflect your latest details and preferences.",
  },
  {
    title: "Restriction & objection",
    description:
      "Pause specific processing activities or opt out of marketing while keeping core services.",
  },
  {
    title: "Erasure",
    description:
      "Request deletion when data is no longer needed, subject to statutory retention duties.",
  },
];

const contactPoints = [
  {
    title: "Data Protection Contact",
    detail: "privacy@hsecommerce.co.uk",
    description:
      "Use this email for privacy requests, DPIAs, or to report a concern.",
    icon: MailCheck,
  },
  {
    title: "Trust & Safety Team",
    detail: "+44 161 123 4000",
    description:
      "Available Monday to Friday for urgent compliance or security queries.",
    icon: Users2,
  },
];

const heroVariants = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0 },
};

const fadeIn = {
  hidden: { opacity: 0, y: 32 },
  visible: (index: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: index * 0.08 },
  }),
};

const PrivacyPage = () => {
  return (
    <div className="bg-white text-foreground">
      <section className="relative overflow-hidden bg-white py-24 md:py-32">
        <div className="relative mx-auto flex max-w-6xl flex-col gap-12 px-4 sm:px-6 md:px-8">
          <motion.div
            initial="hidden"
            animate="visible"
            variants={heroVariants}
            transition={{ duration: 0.8 }}
            className="space-y-8"
          >
            <div className="w-20 h-1 bg-primary" />
            <div className="flex flex-wrap items-center gap-3 text-sm uppercase tracking-widest text-gray-500">
              <span className="border border-gray-200 px-4 py-1">
                Updated · November 2025
              </span>
              <span className=" border border-gray-200 px-4 py-1">
                H&S E-commerce LTD
              </span>
            </div>
            <h1 className="text-4xl font-bold leading-tight text-black sm:text-5xl md:text-6xl lg:text-7xl font-heading">
              Privacy & data protection
            </h1>
            <p className="max-w-3xl text-lg text-gray-600 md:text-xl">
              Transparency, accountability, and trust guide everything we do.
              This privacy statement explains how we collect, use, store, and
              protect your information when you work with our 3PL and logistics
              teams.
            </p>
            <div className="flex flex-wrap gap-4">
              <Link
                href="/contact"
                className="inline-flex items-center gap-3 border border-black px-6 py-3 text-sm font-semibold uppercase tracking-wide hover:bg-black hover:text-white transition-colors"
              >
                Talk to compliance
              </Link>
              <a
                href="mailto:privacy@hsecommerce.co.uk"
                className="inline-flex items-center gap-2 bg-primary px-6 py-3 text-sm font-semibold text-black uppercase tracking-wide"
              >
                Email privacy team
              </a>
            </div>
          </motion.div>
        </div>
      </section>

      <section className="bg-black py-16 md:py-24">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 md:px-8">
          <div className="grid gap-8 md:grid-cols-3">
            {highlightCards.map((card, index) => (
              <motion.div
                key={card.title}
                className=" border border-white/10 bg-[#0d0d0d] p-8"
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.3 }}
                variants={fadeIn}
                custom={index}
              >
                <card.icon className="mb-6 h-10 w-10 text-primary" />
                <h3 className="text-2xl font-semibold text-white font-heading">
                  {card.title}
                </h3>
                <p className="mt-4 text-white/70">{card.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-white py-20 md:py-28">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 md:px-8">
          <div className="mb-16 space-y-6 text-center">
            <p className="text-sm font-semibold uppercase tracking-[0.3em] text-gray-500">
              Your data lifecycle
            </p>
            <h2 className="text-4xl font-bold text-black md:text-5xl font-heading">
              What happens to your information
            </h2>
            <p className="mx-auto max-w-3xl text-lg text-gray-600">
              Below is a transparent breakdown of the way we handle personal and
              operational data from the moment you get in touch with us through
              ongoing fulfilment operations.
            </p>
          </div>

          <div className="grid gap-12 md:grid-cols-2">
            {policySections.map((section, index) => (
              <motion.div
                key={section.title}
                className=" border border-neutral-500/30 bg-white/80 p-8 shadow-2xl backdrop-blur"
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.2 }}
                variants={fadeIn}
                custom={index}
              >
                <div className="mb-6 flex items-center gap-2 text-sm font-semibold uppercase tracking-widest text-primary">
                  <span className="h-1 w-8 bg-primary" />
                  {section.title}
                </div>
                <p className="text-lg text-gray-700">{section.description}</p>
                <ul className="mt-6 space-y-4 text-gray-600">
                  {section.items.map((item) => (
                    <li key={item} className="flex gap-3">
                      <div className="mt-1 h-2.5 w-2.5 bg-primary"></div>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-[#050505] py-20 md:py-28 text-white">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 md:px-8">
          <div className="flex flex-col gap-8 md:flex-row md:items-end md:justify-between">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.3em] text-white/40">
                Your controls
              </p>
              <h3 className="mt-4 text-4xl font-bold font-heading">
                Data subject rights & choices
              </h3>
              <p className="mt-4 max-w-2xl text-white/70">
                We respond to privacy requests within 30 days (or faster for
                critical incidents). Identity verification protects your account
                before we release or delete data.
              </p>
            </div>
            <div className=" border border-white/20 px-4 py-2 text-sm text-white/70">
              Need help? Email privacy@hsecommerce.co.uk
            </div>
          </div>

          <div className="mt-14 grid gap-8 md:grid-cols-2">
            {rightsList.map((right, index) => (
              <motion.div
                key={right.title}
                className=" border border-white/15 bg-white/5 p-8 backdrop-blur"
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.3 }}
                variants={fadeIn}
                custom={index}
              >
                <div className="flex items-center gap-3">
                  <ClipboardCheck className="h-6 w-6 text-primary" />
                  <h4 className="text-2xl font-semibold font-heading">
                    {right.title}
                  </h4>
                </div>
                <p className="mt-4 text-white/70">{right.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-white py-20 md:py-28">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 md:px-8">
          <div className="border border-neutral-500/30 bg-primary p-10 md:p-16">
            <div className="flex flex-col gap-8 md:flex-row md:items-center md:justify-between">
              <div className="max-w-2xl space-y-6">
                <p className="text-sm font-semibold uppercase tracking-[0.3em] text-gray-500">
                  Contact our privacy team
                </p>
                <h3 className="text-4xl font-bold text-black font-heading">
                  We are real people ready to help you stay compliant
                </h3>
                <p className="text-lg text-gray-600">
                  Whether you need a signed DPA, a copy of our security
                  controls, or have a data subject request, the quickest path is
                  to reach out below.
                </p>
              </div>
              <RefreshCcw className="h-16 w-16 text-primary" />
            </div>

            <div className="mt-10 grid gap-6 md:grid-cols-2">
              {contactPoints.map((point) => (
                <div
                  key={point.title}
                  className="border border-neutral-500/30 bg-white p-6 shadow-2xl"
                >
                  <point.icon className="h-8 w-8 text-primary" />
                  <p className="mt-4 text-sm font-semibold uppercase tracking-widest text-gray-500">
                    {point.title}
                  </p>
                  <p className="mt-3 text-2xl font-semibold text-black font-heading">
                    {point.detail}
                  </p>
                  <p className="mt-3 text-gray-600">{point.description}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default PrivacyPage;
